# Generated by Django 5.2.3 on 2025-09-20 18:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du relevé')),
                ('pdf_file', models.FileField(upload_to='bank_statements/', verbose_name='Fichier PDF')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'upload")),
                ('total_transactions', models.IntegerField(default=0, verbose_name='Nombre de transactions')),
                ('final_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Solde final')),
                ('processed', models.BooleanField(default=False, verbose_name='Traité')),
            ],
            options={
                'verbose_name': 'Relevé bancaire',
                'verbose_name_plural': 'Relevés bancaires',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateField(verbose_name='Date opération')),
                ('date_valeur', models.DateField(verbose_name='Date valeur')),
                ('libelle', models.TextField(verbose_name='Libellé')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Débit')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Crédit')),
                ('bank_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banktocsv.bankstatement')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['date_operation'],
            },
        ),
    ]
